blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://github.com/nalabdou/algebra-symfony/tree/main/docs
    about: Read the docs before opening an issue
  - name: Discussions
    url: https://github.com/nalabdou/algebra-symfony/discussions
    about: Questions and general discussion
